### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setPublishableKey' of undefined

### ISSUE THREAD

**Issue by kkoppenhaver** [tyler-johnson/stripe-meteor#19]
Trying to figure out exactly why I'm getting this error. Here's what I have at the moment.

1. Repo cloned into packages/stripe
2. meteor list returns -- mrgalaxy:stripe  1.5.6  Stripe.js and Node-Stripe brought to Meteor.

When I tried to run 'meteor add stripe', I received 'stripe: no such package', so I added it the way it said on Atmosphere. (meteor add mrgalaxy:stripe).  It looks like the JS file is loaded in the browser (<script type="text/javascript" src="/packages/mrgalaxy_stripe.js?e39957bab19924c96cdceccf75e296366a134590"></script>) when I inspect it, but I'm still getting this error, which leads me to believe I'm not including the package correctly.  Any thoughts?  If you need any additional debugging information from me, I'd be happy to provide it.  Thanks for all your work.

**Comment by tyler-johnson** [comment]
I'm going to close this for now as it seems like it has been solved. Please let me know if you are still having trouble.
