### ISSUE TITLE
0.8.1.3 Compatibility

### ISSUE THREAD

**Issue by tejasmanohar** [tyler-johnson/stripe-meteor#20]
I'm on an older project with meteor 0.8.1.3. Does this Stripe package have compatibility with this older meteor version. If not natively, can I use `mrt add ...@...` syntax to install this in a compatible state?

**Comment by tyler-johnson** [comment]
It should still have compatibility with old meteorite installations (via `mrt add stripe`). At the very least, you can always download the repo and include it directly.
