### ISSUE TITLE
mrt:stripe-server

### ISSUE THREAD

**Issue by dandv** [tyler-johnson/stripe-meteor#27]
Is https://atmospherejs.com/mrt/stripe-server an old version of this package by any chance?

If so, can you please unmigrate it, for a cleaner Atmosphere?

If not, can you please flag it?

Thanks.

**Comment by tyler-johnson** [comment]
I flagged it. I think others wanted a package with just node-stripe so that is probably a really old fork. Definitely not added by me... I like clean things.
