### ISSUE TITLE
Can't fetch from host

### ISSUE THREAD

**Issue by jcolemorrison** [tyler-johnson/stripe-meteor#28]
Currently, trying to npm install the package or the tar.gz results in a "forbidden" error:

https://registry.beneaththeink.com/stripe/-/stripe-3.1.0.tgz

Just navigating to that link will tell you what I mean.

Looks like a simple misstep in the npm settings.

**Comment by tyler-johnson** [comment]
Ah yes. It's strange that Meteor decides to publish one's local NPM registry settings. I'll have to figure out how to tell Meteor not to. Thanks for the heads up!

**Comment by JoshDellay** [comment]
Also encountering this error when deploying my app to modulus.

**Comment by jcolemorrison** [comment]
Yeah, if you switch back to the 1.5.6 version it all seems to work fine.

**Comment by JoshDellay** [comment]
As a workaround I went ahead and cloned the repository and made the package a local meteor package.

**Comment by tyler-johnson** [comment]
Alright, this should be fixed with v2.1.0. I have also pushed the `.npm/packages` folder as suggested by Meteor. I hope that solves this.
