### ISSUE TITLE
Support for Managed Accounts

### ISSUE THREAD

**Issue by eventrio** [tyler-johnson/stripe-meteor#33]
I am working on integrating stripe using Stripe Connect and Managed Accounts but your package does not seem to support this functionality. Is there any chance you can update this package to the newest version of the node-stripe package to gain access to this functionality?

I am currently attempting to call:

    Stripe.accounts.create(payload, cb);

But I am getting: 

    Cannot call method 'create' of undefined

pointing to that line in the code.
I am using https://stripe.com/docs/api#account_object as a reference for integration.

Thanks

**Comment by dennisharrison** [comment]
For now use: https://github.com/tyler-johnson/stripe-meteor/pull/32

**Comment by benjick** [comment]
Forked it for real and published https://atmospherejs.com/benjick/stripe @dennisharrison @eventrio until @tyler-johnson comes back

**Comment by VioletaCalvo** [comment]
Thank you!

**Comment by xamlit** [comment]
You rock. Thanks man!

**Comment by BradRyan** [comment]
:+1:

**Comment by generalleger** [comment]
@benjick Thanks!

**Comment by tyler-johnson** [comment]
Stripe has been bumped to 4.0. Thanks!
