### ISSUE TITLE
WrapAsync exported functions

### ISSUE THREAD

**Issue by adamvr** [tyler-johnson/stripe-meteor#35]
It would be nice if we could directly use the functions from this lib in a meteoric way, i.e. `var charge = Stripe.charges.create()`

**Comment by dkmooers** [comment]
You can do this with Meteor.wrapAsync():

http://stackoverflow.com/questions/26226583/meteor-proper-use-of-meteor-wrapasync-on-server
http://stackoverflow.com/questions/26322617/meteor-wrapasync-dont-return-value

**Comment by adamvr** [comment]
Yes, but it would be nice not to.

**Comment by dkmooers** [comment]
@adamvr Did you see this package? (stripe-sync)
https://atmospherejs.com/copleykj/stripe-sync
