### ISSUE TITLE
Bump version to 3.3.4?

### ISSUE THREAD

**Issue by dkmooers** [tyler-johnson/stripe-meteor#36]
Hey Tyler, can you bump the Stripe API version to 3.3.4? There are some new functions like:

Stripe.customers.createSource()

That are not in 3.2.0. Per Stripe API docs, this is the way to add a card to a customer, using a token.

See new version here w/createSource et. al.:

https://github.com/stripe/stripe-node/search?utf8=%E2%9C%93&q=createSource&type=Code

Thanks!

**Comment by Ethaan** [comment]
+1

**Comment by dkmooers** [comment]
Yep, stripe-sync has been updated to include Stripe API 3.3.4, no longer depends on another Stripe package. That's what I'm using. Also nice since it has all the API methods pre-wrapped as sync methods on the server!

https://atmospherejs.com/copleykj/stripe-sync

**Comment by Ethaan** [comment]
Great, i will test it right now

Thanks

**Comment by Ethaan** [comment]
Qucik question.

How you deal with the cosole warn.

```It looks like Stripe.js was loaded more than one time. Please only load it once per page.?```

**Comment by dkmooers** [comment]
Remove mrgalaxy:stripe from your project and you should be good. stripe-sync now includes Stripe javascript libraries.

**Comment by tyler-johnson** [comment]
I've bumped Stripe to 4.0. Let me know if there are issues.
