### ISSUE TITLE
stripe.subscriptions undefined?

### ISSUE THREAD

**Issue by quape** [tyler-johnson/stripe-meteor#53]
Hi there,

I'm trying to create a new subscription, but `stripe.subscriptions.create()` results in this error: 

`TypeError: Cannot read property 'create' of undefined`

What's that? Everything else what I did with stripe worked so far.

Greetings
Mat

**Comment by wonderfulazzahra** [comment]
i got this error too :(

thanks
azzahra

**Comment by AnujSharma1459** [comment]
I got this error too.
What to do now??

**Comment by quape** [comment]
I think this package doesn't support the new methods. Use `stripe.customers.createSubscription` instead. This is what I did at this point. Or, even better, don't use this package anymore but use the stripe npm package instead. `meteor npm install stripe --save` and then use stripe with `var stripe = require('stripe')(PRIVATE_KEY)`

**Comment by AnujSharma1459** [comment]
Thanks quape.
You save my day.
