### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by derwaldgeist** [tyler-johnson/stripe-meteor#54]
I've seen that the last commit is from 10 months ago, and the Stripe libraries are not up-to-date. Is this package still being maintained?

**Comment by loanlaux** [comment]
Doesn't seem like it's maintained anymore. Couldn't get it to work with my app.

**Comment by layik** [comment]
I can get it to work with Android and even Safari iOS (opening new window) but does not work on iOS app @loanlaux

**Comment by derwaldgeist** [comment]
Closing this. Dead package, it seems.
